apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: airflow
    app.kubernetes.io/part-of: airflow
  name: airflow-server-external
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  #loadBalancerIP: 10.211.1.0
  selector:
    app.kubernetes.io/name: airflow