apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: datahub-frontend
    app.kubernetes.io/part-of: datahub
  name: datahub-frontend-internal
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9002
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: datahub
    app.kubernetes.io/name: datahub-frontend