apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: superset-frontend
    app.kubernetes.io/part-of: superset
  name: superset-frontend-internal
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8088
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: superset
    app.kubernetes.io/name: superset-frontend